// ---------------------------------------------------------------------------
// Central game registry — the single source of truth for the game catalog.
//
// The homepage, /games page and /games/[gameId] placeholder all render from
// this data. To ship a new game: implement it, flip `status` to 'live' and
// point `route` at its real page — nothing else needs to change.
// ---------------------------------------------------------------------------

export type GameStatus = 'live';

export type CategoryId =
  | 'icebreakers'
  | 'speed'
  | 'guessing'
  | 'estimation'
  | 'funny'
  | 'developer'
  | 'creative'
  | 'word'
  | 'competitive'
  | 'agile';

export interface Game {
  id: string;
  name: string;
  category: CategoryId;
  description: string;
  icon: string;
  status: GameStatus;
  /** Where the game actually lives. Live games use their real route. */
  route: string;
  players: string;
  duration: string;
}

export interface GameCategory {
  id: CategoryId;
  name: string;
  /** Short label used in filter chips. */
  short: string;
  icon: string;
  description: string;
}

// ---------------------------------------------------------------------------
// Categories
// ---------------------------------------------------------------------------

export const CATEGORIES: GameCategory[] = [
  { id: 'icebreakers', name: 'Retrospective & Team Icebreakers', short: 'Icebreakers', icon: '🧊', description: 'Warm the team up with quick questions, check-ins and shared laughs.' },
  { id: 'speed', name: 'Fast Reaction & Speed', short: 'Speed', icon: '⚡', description: 'How fast can your team think? Race the clock and find out.' },
  { id: 'guessing', name: 'Guessing Games', short: 'Guessing', icon: '🧠', description: 'Test how well your team knows movies, songs, logos and each other.' },
  { id: 'estimation', name: 'Estimation Games', short: 'Estimation', icon: '🎯', description: 'Guesstimate, compare and see who lands closest.' },
  { id: 'funny', name: 'Funny & Social', short: 'Funny', icon: '😂', description: 'Silly prompts, punchlines and office inside jokes.' },
  { id: 'developer', name: 'Developer Games', short: 'Developer', icon: '💻', description: 'Code trivia, bugs and broken builds — for teams that ship.' },
  { id: 'creative', name: 'Creative Games', short: 'Creative', icon: '✍️', description: 'Draw, write and improvise something new together.' },
  { id: 'word', name: 'Word Games', short: 'Word', icon: '🔤', description: 'Quick thinking, faster fingers, one letter at a time.' },
  { id: 'competitive', name: 'Competitive Games', short: 'Competitive', icon: '🏆', description: 'Battle it out, stack points and climb the leaderboard.' },
  { id: 'agile', name: 'Agile Activities', short: 'Agile', icon: '🔄', description: 'Hosted ceremonies for the sprint — team health checks, live polls and quick decisions.' },
];

export const CATEGORY_IDS: CategoryId[] = CATEGORIES.map((c) => c.id);

export function getCategory(id: string): GameCategory | undefined {
  return CATEGORIES.find((c) => c.id === id);
}

// ---------------------------------------------------------------------------
// Games (110 total, numbered to match the product backlog)
// ---------------------------------------------------------------------------

const liveGame = (
  id: string,
  category: CategoryId,
  name: string,
  description: string,
  icon: string,
  players = '3–20 players',
  duration = '5 min',
): Game => ({
  id,
  name,
  category,
  description,
  icon,
  status: 'live',
  route: `/games/${id}`,
  players,
  duration,
});

export const GAMES: Game[] = [
  // --- 🔄 Agile Activities (hosted ceremonies) --------------------------------
  {
    id: 'team-health',
    name: 'Team Health Check',
    category: 'agile',
    description: 'Rate communication, delivery, morale and more — spot team health trends before they bite.',
    icon: '❤️',
    status: 'live',
    route: '/games/team-health',
    players: '3–20 players',
    duration: '5 min',
  },
  {
    id: 'live-poll',
    name: 'Live Poll',
    category: 'agile',
    description: 'Ask the room a question, collect votes in real time and reveal the split.',
    icon: '🗳️',
    status: 'live',
    route: '/games/live-poll',
    players: '3–20 players',
    duration: '2 min',
  },

  // --- 🧊 Icebreakers (1–15) -------------------------------------------------
  {
    id: 'most-likely-to',
    name: 'Most Likely To',
    category: 'icebreakers',
    description: 'Vote for the teammate most likely to do it — yes, that one. Live now.',
    icon: '😂',
    status: 'live',
    route: '/games/most-likely-to',
    players: '3–20 players',
    duration: '5 min',
  },
  {
    id: 'would-you-rather',
    name: 'Would You Rather',
    category: 'icebreakers',
    description: 'Tough picks, hot takes, zero right answers. Live now.',
    icon: '🤔',
    status: 'live',
    route: '/games/would-you-rather',
    players: '3–20 players',
    duration: '5 min',
  },
  {
    id: 'this-or-that',
    name: 'This or That',
    category: 'icebreakers',
    description: 'Pick a side and defend it for 10 seconds. Live now.',
    icon: '⚖️',
    status: 'live',
    route: '/games/this-or-that',
    players: '3–20 players',
    duration: '5 min',
  },
  liveGame('two-truths-and-a-lie', 'icebreakers', 'Two Truths & a Lie', 'Spot the lie before the room votes you out.', '🕵️'),
  {
    id: 'who-said-it',
    name: 'Who Said It?',
    category: 'icebreakers',
    description: 'Guess which teammate actually said that quote. Live now.',
    icon: '💬',
    status: 'live',
    route: '/games/who-said-it',
    players: '3–20 players',
    duration: '5 min',
  },
  liveGame('guess-who', 'icebreakers', 'Guess Who', 'A teammate describes themselves — the room guesses who.', '🫣'),
  {
    id: 'team-superlatives',
    name: 'Team Superlatives',
    category: 'icebreakers',
    description: 'Crown the teammate most likely to win every category. Live now.',
    icon: '🏅',
    status: 'live',
    route: '/games/team-superlatives',
    players: '3–20 players',
    duration: '5 min',
  },
  liveGame('who-knows-the-team-best', 'icebreakers', 'Who Knows the Team Best?', 'Answer team questions. Compare answers. Laugh.', '🎓'),
  liveGame('human-bingo', 'icebreakers', 'Human Bingo', 'Fill your card with teammates who match the squares.', '🟩'),
  {
    id: 'team-trivia',
    name: 'Team Trivia',
    category: 'icebreakers',
    description: 'Trivia about the team, for the team. Live now.',
    icon: '🧠',
    status: 'live',
    route: '/games/team-trivia',
    players: '3–20 players',
    duration: '5 min',
  },
  {
    id: 'emoji-check-in',
    name: 'Emoji Check-in',
    category: 'icebreakers',
    description: 'How are you really doing? Pick one emoji. Live now.',
    icon: '🙂',
    status: 'live',
    route: '/games/emoji-check-in',
    players: '3–20 players',
    duration: '5 min',
  },
  liveGame('one-word-check-in', 'icebreakers', 'One Word Check-in', 'Describe your week in a single word. Go.', '🗣️'),
  liveGame('rose-thorn-bud', 'icebreakers', 'Rose, Thorn & Bud', 'Share a win, a struggle and something you look forward to.', '🌹'),
  liveGame('high-low-buffalo', 'icebreakers', 'High, Low, Buffalo', 'The classic daily standup round, gamified.', '🦬'),
  {
    id: 'guess-the-mood',
    name: 'Guess the Mood',
    category: 'icebreakers',
    description: 'Rate the vibe. See who reads the room best. Live now.',
    icon: '🎭',
    status: 'live',
    route: '/games/guess-the-mood',
    players: '3–20 players',
    duration: '5 min',
  },

  // --- ⚡ Fast Reaction & Speed (16–27) --------------------------------------
  liveGame('fastest-finger', 'speed', 'Fastest Finger', 'First to tap the right answer takes the point.', '👆'),
  {
    id: 'quick-math',
    name: 'Quick Math',
    category: 'speed',
    description: 'Arithmetic under pressure — calculators banned. Live now.',
    icon: '🧮',
    status: 'live',
    route: '/games/quick-math',
    players: '3–20 players',
    duration: '5 min',
  },
  {
    id: 'speed-quiz',
    name: 'Speed Quiz',
    category: 'speed',
    description: 'A quiz where every second counts. Live now.',
    icon: '⏱️',
    status: 'live',
    route: '/games/speed-quiz',
    players: '3–20 players',
    duration: '5 min',
  },
  {
    id: 'word-scramble',
    name: 'Word Scramble',
    category: 'speed',
    description: 'Unscramble the word before the timer runs out. Live now.',
    icon: '🔀',
    status: 'live',
    route: '/games/word-scramble',
    players: '3–20 players',
    duration: '5 min',
  },
  {
    id: 'anagram-race',
    name: 'Anagram Race',
    category: 'speed',
    description: 'Rearrange the letters. Race your teammates. Live now.',
    icon: '🔄',
    status: 'live',
    route: '/games/anagram-race',
    players: '3–20 players',
    duration: '5 min',
  },
  {
    id: 'missing-letter',
    name: 'Missing Letter',
    category: 'speed',
    description: 'Spot the letter that keeps the word alive. Live now.',
    icon: '🔤',
    status: 'live',
    route: '/games/missing-letter',
    players: '3–20 players',
    duration: '5 min',
  },
  {
    id: 'odd-one-out',
    name: 'Odd One Out',
    category: 'speed',
    description: 'Four options. Three fit. Find the imposter. Live now.',
    icon: '🥷',
    status: 'live',
    route: '/games/odd-one-out',
    players: '3–20 players',
    duration: '5 min',
  },
  {
    id: 'pattern-puzzle',
    name: 'Pattern Puzzle',
    category: 'speed',
    description: 'Spot the pattern faster than everyone else. Live now.',
    icon: '🧩',
    status: 'live',
    route: '/games/pattern-puzzle',
    players: '3–20 players',
    duration: '5 min',
  },
  liveGame('memory-challenge', 'speed', 'Memory Challenge', 'Memorize the sequence. Then it disappears.', '🧠'),
  liveGame('reaction-challenge', 'speed', 'Reaction Challenge', 'Tap when the screen changes. Don’t be last.', '⚡'),
  liveGame('typing-race', 'speed', 'Typing Race', 'First to type the sentence wins the round.', '⌨️'),
  liveGame('category-blitz', 'speed', 'Category Blitz', 'Name something in the category — fast, fast, fast.', '🎲'),

  // --- 🧠 Guessing (28–39) ---------------------------------------------------
  {
    id: 'emoji-guess',
    name: 'Emoji Guess',
    category: 'guessing',
    description: 'Decode the movie, phrase or song from emojis. Live now.',
    icon: '🫠',
    status: 'live',
    route: '/games/emoji-guess',
    players: '3–20 players',
    duration: '5 min',
  },
  {
    id: 'movie-guess',
    name: 'Movie Guess',
    category: 'guessing',
    description: 'Guess the film from a single screenshot. Live now.',
    icon: '🎬',
    status: 'live',
    route: '/games/movie-guess',
    players: '3–20 players',
    duration: '5 min',
  },
  liveGame('song-guess', 'guessing', 'Song Guess', 'Name that tune — first notes only.', '🎵'),
  {
    id: 'logo-guess',
    name: 'Logo Guess',
    category: 'guessing',
    description: 'Zoomed-out logos. Can you name them all? Live now.',
    icon: '🏷️',
    status: 'live',
    route: '/games/logo-guess',
    players: '3–20 players',
    duration: '5 min',
  },
  {
    id: 'famous-person-guess',
    name: 'Famous Person Guess',
    category: 'guessing',
    description: 'Clues drop one by one. Guess before the room does. Live now.',
    icon: '🌟',
    status: 'live',
    route: '/games/famous-person-guess',
    players: '3–20 players',
    duration: '5 min',
  },
  {
    id: 'country-guess',
    name: 'Country Guess',
    category: 'guessing',
    description: 'Guess the country from a shape, flag or food. Live now.',
    icon: '🌍',
    status: 'live',
    route: '/games/country-guess',
    players: '3–20 players',
    duration: '5 min',
  },
  {
    id: 'image-guess',
    name: 'Image Guess',
    category: 'guessing',
    description: 'What is this a photo of? Be specific. Live now.',
    icon: '🖼️',
    status: 'live',
    route: '/games/image-guess',
    players: '3–20 players',
    duration: '5 min',
  },
  {
    id: 'zoomed-in-guess',
    name: 'Zoomed-In Guess',
    category: 'guessing',
    description: 'Extreme close-ups of everyday objects. Live now.',
    icon: '🔬',
    status: 'live',
    route: '/games/zoomed-in-guess',
    players: '3–20 players',
    duration: '5 min',
  },
  liveGame('sound-guess', 'guessing', 'Sound Guess', 'Name it by sound alone.', '🔊'),
  {
    id: 'mystery-word',
    name: 'Mystery Word',
    category: 'guessing',
    description: 'One word, endless guesses, shared letters only. Live now.',
    icon: '🕵️‍♀️',
    status: 'live',
    route: '/games/mystery-word',
    players: '3–20 players',
    duration: '5 min',
  },
  liveGame('20-questions', 'guessing', '20 Questions', 'Twenty yes-or-no questions to crack the answer.', '❓'),
  {
    id: 'higher-or-lower',
    name: 'Higher or Lower',
    category: 'guessing',
    description: 'Guess whether the number goes up or down. Live now.',
    icon: '📈',
    status: 'live',
    route: '/games/higher-or-lower',
    players: '3–20 players',
    duration: '5 min',
  },

  // --- 🎯 Estimation (40–46) -------------------------------------------------
  {
    id: 'estimation-battle',
    name: 'Estimation Battle',
    category: 'estimation',
    description: 'Everyone estimates. Closest to the truth wins. Live now.',
    icon: '⚔️',
    status: 'live',
    route: '/games/estimation-battle',
    players: '3–20 players',
    duration: '5 min',
  },
  {
    id: 'price-is-right',
    name: 'Price Is Right',
    category: 'estimation',
    description: 'Guess the price — without going over. Live now.',
    icon: '💸',
    status: 'live',
    route: '/games/price-is-right',
    players: '3–20 players',
    duration: '5 min',
  },
  {
    id: 'how-many',
    name: 'How Many?',
    category: 'estimation',
    description: 'Jelly beans in the jar. Guess the count. Live now.',
    icon: '🫙',
    status: 'live',
    route: '/games/how-many',
    players: '3–20 players',
    duration: '5 min',
  },
  {
    id: 'closest-wins',
    name: 'Closest Wins',
    category: 'estimation',
    description: 'Estimate, compare, closest takes the point. Live now.',
    icon: '🎯',
    status: 'live',
    route: '/games/closest-wins',
    players: '3–20 players',
    duration: '5 min',
  },
  {
    id: 'higher-lower',
    name: 'Higher / Lower',
    category: 'estimation',
    description: 'Estimate the stat, then guess higher or lower. Live now.',
    icon: '↕️',
    status: 'live',
    route: '/games/higher-lower',
    players: '3–20 players',
    duration: '5 min',
  },
  {
    id: 'planning-poker',
    name: 'Planning Poker',
    category: 'estimation',
    description: 'Estimate together, reveal together. The classic sprint-planning game — live now.',
    icon: '🃏',
    status: 'live',
    route: '/create',
    players: '2–20 players',
    duration: '10 min',
  },
  {
    id: 'team-estimation',
    name: 'Team Estimation',
    category: 'estimation',
    description: 'Estimate as a team and defend your number. Live now.',
    icon: '🤝',
    status: 'live',
    route: '/games/team-estimation',
    players: '3–20 players',
    duration: '5 min',
  },

  // --- 😂 Funny & Social (47–60) --------------------------------------------
  liveGame('caption-this', 'funny', 'Caption This', 'Everyone captions the same image. Vote the best.', '🖊️'),
  liveGame('bad-advice', 'funny', 'Bad Advice', 'Give the worst possible advice. On purpose.', '🙃'),
  liveGame('wrong-answers-only', 'funny', 'Wrong Answers Only', 'Answer trivia as incorrectly as possible.', '🚫'),
  liveGame('finish-the-sentence', 'funny', 'Finish the Sentence', 'Start a sentence, let the team finish it hilariously.', '✂️'),
  liveGame('complete-the-meme', 'funny', 'Complete the Meme', 'Top text, bottom text, your best lines.', '🎭'),
  liveGame('pun-battle', 'funny', 'Pun Battle', 'Best pun wins the round. No groaning allowed.', '🎤'),
  liveGame('roast-the-scenario', 'funny', 'Roast the Scenario', 'The most awkward work situation — roast it.', '🔥'),
  liveGame('excuse-generator', 'funny', 'Excuse Generator', 'Generate excuses, vote the most believable.', '🦥'),
  liveGame('office-excuse-battle', 'funny', 'Office Excuse Battle', '“The dog ate my ticket” — make it work.', '🐶'),
  liveGame('fake-product', 'funny', 'Fake Product', 'Invent a ridiculous product and pitch it.', '📦'),
  liveGame('fake-startup', 'funny', 'Fake Startup', 'Pitch a startup so bad it’s brilliant.', '🚀'),
  liveGame('worst-feature-ever', 'funny', 'Worst Feature Ever', 'Design the feature no user asked for.', '💣'),
  {
    id: 'bug-or-feature',
    name: 'Bug or Feature?',
    category: 'funny',
    description: 'Is it broken or is it intended? The team decides. Live now.',
    icon: '🐛',
    status: 'live',
    route: '/games/bug-or-feature',
    players: '3–20 players',
    duration: '5 min',
  },
  liveGame('developer-translator', 'funny', 'Developer Translator', 'Translate “it works on my machine” into business speak.', '🔁'),

  // --- 💻 Developer (61–75) --------------------------------------------------
  {
    id: 'guess-the-error',
    name: 'Guess the Error',
    category: 'developer',
    description: 'A stack trace, one chance. What broke? Live now.',
    icon: '🚨',
    status: 'live',
    route: '/games/guess-the-error',
    players: '3–20 players',
    duration: '5 min',
  },
  {
    id: 'guess-the-output',
    name: 'Guess the Output',
    category: 'developer',
    description: 'Read the snippet. Predict the console output. Live now.',
    icon: '🖥️',
    status: 'live',
    route: '/games/guess-the-output',
    players: '3–20 players',
    duration: '5 min',
  },
  {
    id: 'code-trivia',
    name: 'Code Trivia',
    category: 'developer',
    description: 'Programming history, languages and lore. Live now.',
    icon: '📚',
    status: 'live',
    route: '/games/code-trivia',
    players: '3–20 players',
    duration: '5 min',
  },
  {
    id: 'tech-logo-guess',
    name: 'Tech Logo Guess',
    category: 'developer',
    description: 'Frameworks, clouds and tools — by logo. Live now.',
    icon: '🔷',
    status: 'live',
    route: '/games/tech-logo-guess',
    players: '3–20 players',
    duration: '5 min',
  },
  {
    id: 'programming-language-guess',
    name: 'Programming Language Guess',
    category: 'developer',
    description: 'Name the language from its quirkiest snippet. Live now.',
    icon: '🐍',
    status: 'live',
    route: '/games/programming-language-guess',
    players: '3–20 players',
    duration: '5 min',
  },
  {
    id: 'guess-the-git-command',
    name: 'Guess the Git Command',
    category: 'developer',
    description: 'Untangle the mess with the right command. Live now.',
    icon: '🔀',
    status: 'live',
    route: '/games/guess-the-git-command',
    players: '3–20 players',
    duration: '5 min',
  },
  {
    id: 'http-status-challenge',
    name: 'HTTP Status Challenge',
    category: 'developer',
    description: 'What status code does that situation deserve? Live now.',
    icon: '🔣',
    status: 'live',
    route: '/games/http-status-challenge',
    players: '3–20 players',
    duration: '5 min',
  },
  {
    id: 'regex-challenge',
    name: 'Regex Challenge',
    category: 'developer',
    description: 'Match the pattern. Escape the chaos. Live now.',
    icon: '🎯',
    status: 'live',
    route: '/games/regex-challenge',
    players: '3–20 players',
    duration: '5 min',
  },
  {
    id: 'sql-challenge',
    name: 'SQL Challenge',
    category: 'developer',
    description: 'Write the query that answers the question. Live now.',
    icon: '🗄️',
    status: 'live',
    route: '/games/sql-challenge',
    players: '3–20 players',
    duration: '5 min',
  },
  {
    id: 'debugging-race',
    name: 'Debugging Race',
    category: 'developer',
    description: 'Find the bug before your teammates do. Live now.',
    icon: '🐞',
    status: 'live',
    route: '/games/debugging-race',
    players: '3–20 players',
    duration: '5 min',
  },
  {
    id: 'code-scramble',
    name: 'Code Scramble',
    category: 'developer',
    description: 'Rearrange the lines into working code. Live now.',
    icon: '🔀',
    status: 'live',
    route: '/games/code-scramble',
    players: '3–20 players',
    duration: '5 min',
  },
  {
    id: 'tech-acronym-quiz',
    name: 'Tech Acronym Quiz',
    category: 'developer',
    description: 'What does that three-letter acronym mean? Live now.',
    icon: '🔡',
    status: 'live',
    route: '/games/tech-acronym-quiz',
    players: '3–20 players',
    duration: '5 min',
  },
  {
    id: 'guess-the-framework',
    name: 'Guess the Framework',
    category: 'developer',
    description: 'Identify the framework from its boilerplate. Live now.',
    icon: '🧱',
    status: 'live',
    route: '/games/guess-the-framework',
    players: '3–20 players',
    duration: '5 min',
  },
  {
    id: 'stack-overflow-challenge',
    name: 'Stack Overflow Challenge',
    category: 'developer',
    description: 'Match the question to its legendary answer. Live now.',
    icon: '📋',
    status: 'live',
    route: '/games/stack-overflow-challenge',
    players: '3–20 players',
    duration: '5 min',
  },
  {
    id: 'developer-meme-guess',
    name: 'Developer Meme Guess',
    category: 'developer',
    description: 'Caption, identify and rate the dev memes. Live now.',
    icon: '😅',
    status: 'live',
    route: '/games/developer-meme-guess',
    players: '3–20 players',
    duration: '5 min',
  },

  // --- ✍️ Creative (76–87) ---------------------------------------------------
  liveGame('draw-and-guess', 'creative', 'Draw & Guess', 'Sketch it fast, guess it faster.', '🎨'),
  liveGame('one-line-story', 'creative', 'One-Line Story', 'Everyone adds one line. Chaos becomes canon.', '📖'),
  liveGame('story-chain', 'creative', 'Story Chain', 'Pass the story around, one twist at a time.', '⛓️'),
  liveGame('build-a-story', 'creative', 'Build a Story', 'Vote on the best next beat for the group story.', '🏗️'),
  liveGame('doodle-battle', 'creative', 'Doodle Battle', 'Best doodle for the prompt wins the round.', '✏️'),
  liveGame('logo-drawing', 'creative', 'Logo Drawing', 'Recreate a famous logo from memory.', '🏷️'),
  liveGame('draw-without-words', 'creative', 'Draw Without Words', 'No letters, no numbers — only shapes.', '🔇'),
  liveGame('describe-and-draw', 'creative', 'Describe & Draw', 'Describe it, teammate draws what they hear.', '🗣️'),
  liveGame('emoji-story', 'creative', 'Emoji Story', 'Tell a whole story using only emojis.', '🫧'),
  liveGame('create-a-meme', 'creative', 'Create a Meme', 'Template provided. Punchline is on you.', '🖼️'),
  liveGame('name-that-product', 'creative', 'Name That Product', 'Invent a product, then invent its name.', '🏷️'),
  liveGame('tagline-battle', 'creative', 'Tagline Battle', 'One product, ten taglines, one winner.', '💬'),

  // --- 🔤 Word (88–100) ------------------------------------------------------
  liveGame('word-chain', 'word', 'Word Chain', 'Last letter becomes the next word’s first.', '⛓️'),
  liveGame('word-association', 'word', 'Word Association', 'Say the first word that comes to mind.', '🧠'),
  liveGame('last-letter', 'word', 'Last Letter', 'New word, last letter of the previous one. Fast.', '🔚'),
  liveGame('forbidden-word', 'word', 'Forbidden Word', 'Describe it without saying the obvious word.', '🚫'),
  {
    id: 'unscramble',
    name: 'Unscramble',
    category: 'word',
    description: 'Mixed-up letters, one clear word. Live now.',
    icon: '🫧',
    status: 'live',
    route: '/games/unscramble',
    players: '3–20 players',
    duration: '5 min',
  },
  liveGame('hangman', 'word', 'Hangman', 'The classic. One wrong guess from the gallows.', '🪢'),
  liveGame('wordle-multiplayer', 'word', 'Wordle-style Multiplayer', 'Guess the word in five tries — together.', '🟩'),
  {
    id: 'guess-the-word',
    name: 'Guess the Word',
    category: 'word',
    description: 'Clues drop, letters fill, team guesses. Live now.',
    icon: '🔤',
    status: 'live',
    route: '/games/guess-the-word',
    players: '3–20 players',
    duration: '5 min',
  },
  liveGame('alphabet-challenge', 'word', 'Alphabet Challenge', 'Words in alphabetical order, under pressure.', '🔠'),
  liveGame('categories', 'word', 'Categories', 'Stop! Name five things in the category.', '🛑'),
  liveGame('rhyming-battle', 'word', 'Rhyming Battle', 'Rhyme on command or bow out.', '🎤'),
  {
    id: 'synonym-race',
    name: 'Synonym Race',
    category: 'word',
    description: 'Another way to say it — race the clock. Live now.',
    icon: '🔄',
    status: 'live',
    route: '/games/synonym-race',
    players: '3–20 players',
    duration: '5 min',
  },
  {
    id: 'opposite-challenge',
    name: 'Opposite Challenge',
    category: 'word',
    description: 'Say the opposite. Faster than everyone. Live now.',
    icon: '⚖️',
    status: 'live',
    route: '/games/opposite-challenge',
    players: '3–20 players',
    duration: '5 min',
  },

  // --- 🏆 Competitive (101–110) ----------------------------------------------
  {
    id: 'trivia-battle',
    name: 'Trivia Battle',
    category: 'competitive',
    description: 'Head-to-head trivia across every topic. Live now.',
    icon: '⚔️',
    status: 'live',
    route: '/games/trivia-battle',
    players: '3–20 players',
    duration: '5 min',
  },
  {
    id: 'quiz-royale',
    name: 'Quiz Royale',
    category: 'competitive',
    description: 'Everyone answers. Wrong answers get voted out. Live now.',
    icon: '👑',
    status: 'live',
    route: '/games/quiz-royale',
    players: '3–20 players',
    duration: '5 min',
  },
  {
    id: 'survival-quiz',
    name: 'Survival Quiz',
    category: 'competitive',
    description: 'Last one standing with correct answers wins. Live now.',
    icon: '🪖',
    status: 'live',
    route: '/games/survival-quiz',
    players: '3–20 players',
    duration: '5 min',
  },
  {
    id: 'last-player-standing',
    name: 'Last Player Standing',
    category: 'competitive',
    description: 'Keep answering, keep surviving. Live now.',
    icon: '🏅',
    status: 'live',
    route: '/games/last-player-standing',
    players: '3–20 players',
    duration: '5 min',
  },
  {
    id: 'point-rush',
    name: 'Point Rush',
    category: 'competitive',
    description: 'Stack points fast in rapid-fire rounds. Live now.',
    icon: '⚡',
    status: 'live',
    route: '/games/point-rush',
    players: '3–20 players',
    duration: '5 min',
  },
  {
    id: 'team-vs-team-quiz',
    name: 'Team vs Team Quiz',
    category: 'competitive',
    description: 'Two teams, one buzzer, bragging rights. Live now.',
    icon: '🆚',
    status: 'live',
    route: '/games/team-vs-team-quiz',
    players: '3–20 players',
    duration: '5 min',
  },
  {
    id: 'speed-round',
    name: 'Speed Round',
    category: 'competitive',
    description: 'Rapid questions, even faster answers. Live now.',
    icon: '⏩',
    status: 'live',
    route: '/games/speed-round',
    players: '3–20 players',
    duration: '5 min',
  },
  {
    id: 'lightning-round',
    name: 'Lightning Round',
    category: 'competitive',
    description: 'No time to think — just answer. Live now.',
    icon: '🌩️',
    status: 'live',
    route: '/games/lightning-round',
    players: '3–20 players',
    duration: '5 min',
  },
  {
    id: 'knockout',
    name: 'Knockout',
    category: 'competitive',
    description: 'One wrong answer and you’re out. Live now.',
    icon: '🥊',
    status: 'live',
    route: '/games/knockout',
    players: '3–20 players',
    duration: '5 min',
  },
  {
    id: 'leaderboard-challenge',
    name: 'Leaderboard Challenge',
    category: 'competitive',
    description: 'Climb the board round after round. Live now.',
    icon: '📊',
    status: 'live',
    route: '/games/leaderboard-challenge',
    players: '3–20 players',
    duration: '5 min',
  },
];

export const GAME_COUNT = GAMES.length;

export function getGame(id: string): Game | undefined {
  return GAMES.find((g) => g.id === id);
}

export function gamesByCategory(category: CategoryId): Game[] {
  return GAMES.filter((g) => g.category === category);
}

/** Live games currently playable. */
export const LIVE_GAMES = GAMES.filter((g) => g.status === 'live');
