/**
 * Client-side config for the engine-backed games.
 *
 * The server owns the game rules and the prompt banks (server/games/registry.mjs
 * + server/games/data/*.json). This file is the *client* half of that registry:
 * it tells the shared GameRoom component which socket event to emit for a vote,
 * how to render the round, and what copy to show. Adding a game here + on the
 * server + in the catalog (src/lib/games.ts) ships it — no new page needed.
 */

import type { Accent } from './types';

export type GameKind = 'options' | 'teammate' | 'quiz' | 'estimate' | 'free' | 'health' | 'poll';

export interface GameConfig {
  id: string;
  kind: GameKind;
  /** Socket event the client emits to cast this game's vote (or submit an answer). */
  castEvent: string;
  /** `free` games only: the event the client emits during the vote phase. */
  voteEvent?: string;
  /** `free` games only: whether the room votes on the best answer after revealing. */
  hasVote?: boolean;
  icon: string;
  accent: Accent;
  title: string;
  /** One-line description shown on the create screen. */
  tagline: string;
  /** Header chip, e.g. "😂 Most Likely To". */
  header: string;
  /** Waiting-room start button. */
  startLabel: string;
  /** Lead-in above the prompt (or question). */
  promptLead: string;
  /** "X / Y picked", "X / Y chosen", "X / Y answered", "X / Y guessed". */
  progressVerb: string;
  /** "Everyone has picked", "Everyone has chosen", … */
  everyoneDone: string;
  /** Gold reveal button. */
  revealLabel: string;
  /** "Next Prompt", "Next Dilemma", "Next Question", "Next Round". */
  nextLabel: string;
  /** Results section title: "Who picked whom", "Who chose what", … */
  whoTitle: string;
  /** Sidebar status after voting: "Picked", "Chose", "Answered", "Guessed". */
  doneLabel: string;
  /** Sidebar note about privacy. */
  sideNote: string;
  /** Waiting-room sub copy for non-hosts. */
  waitingSub: string;
}

/** Kind-level defaults — games only override what differs. */
const KIND_DEFAULTS: Record<GameKind, Omit<GameConfig, 'id' | 'kind' | 'castEvent' | 'icon' | 'accent' | 'title' | 'tagline' | 'header' | 'promptLead'>> = {
  teammate: {
    startLabel: 'Start the First Prompt',
    progressVerb: 'picked',
    everyoneDone: 'Everyone has picked',
    revealLabel: 'Reveal the Votes',
    nextLabel: 'Next Prompt',
    whoTitle: 'Who picked whom',
    doneLabel: 'Picked',
    sideNote: 'Picks stay hidden until the host reveals the round.',
    waitingSub: 'The host will start the first prompt when everyone’s here.',
  },
  options: {
    startLabel: 'Start the First Round',
    progressVerb: 'chosen',
    everyoneDone: 'Everyone has chosen',
    revealLabel: 'Reveal the Split',
    nextLabel: 'Next Round',
    whoTitle: 'Who chose what',
    doneLabel: 'Chose',
    sideNote: 'Choices stay hidden until the host reveals the round.',
    waitingSub: 'The host will start the first round when everyone’s here.',
  },
  quiz: {
    startLabel: 'Start the First Question',
    progressVerb: 'answered',
    everyoneDone: 'Everyone has answered',
    revealLabel: 'Reveal the Answers',
    nextLabel: 'Next Question',
    whoTitle: 'Who answered what',
    doneLabel: 'Answered',
    sideNote: 'Answers stay hidden until the host reveals the round.',
    waitingSub: 'The host will start the first question when everyone’s here.',
  },
  estimate: {
    startLabel: 'Start the First Guess',
    progressVerb: 'guessed',
    everyoneDone: 'Everyone has guessed',
    revealLabel: 'Reveal the Guesses',
    nextLabel: 'Next Round',
    whoTitle: 'Who guessed what',
    doneLabel: 'Guessed',
    sideNote: 'Guesses stay hidden until the host reveals the round.',
    waitingSub: 'The host will start the first round when everyone’s here.',
  },
  free: {
    startLabel: 'Start the First Round',
    progressVerb: 'submitted',
    everyoneDone: 'Everyone has submitted',
    revealLabel: 'Reveal the Answers',
    nextLabel: 'Next Round',
    whoTitle: 'Who submitted what',
    doneLabel: 'Submitted',
    sideNote: 'Answers stay hidden until the host reveals them.',
    waitingSub: 'The host will start the first round when everyone’s here.',
  },
  health: {
    startLabel: 'Start Health Check',
    progressVerb: 'submitted',
    everyoneDone: 'Everyone has submitted',
    revealLabel: 'Reveal Results',
    nextLabel: 'New Health Check',
    whoTitle: 'Who rated what',
    doneLabel: 'Submitted',
    sideNote: 'Ratings stay hidden until the host reveals them.',
    waitingSub: 'The host will start the health check when everyone’s here.',
  },
  poll: {
    startLabel: 'Start Poll',
    progressVerb: 'voted',
    everyoneDone: 'Everyone has voted',
    revealLabel: 'Reveal Results',
    nextLabel: 'New Poll',
    whoTitle: 'Who voted what',
    doneLabel: 'Voted',
    sideNote: 'Votes stay hidden until the host reveals them.',
    waitingSub: 'The host will start the poll when everyone’s here.',
  },
};

interface ConfigSeed {
  id: string;
  kind: GameKind;
  castEvent: string;
  /** `free` games only — the event used during the vote phase. */
  voteEvent?: string;
  /** `free` games only — the room picks the best answer after revealing. */
  hasVote?: boolean;
  icon: string;
  accent: Accent;
  title: string;
  tagline: string;
  header: string;
  promptLead: string;
  startLabel?: string;
  progressVerb?: string;
  everyoneDone?: string;
  revealLabel?: string;
  nextLabel?: string;
  whoTitle?: string;
  doneLabel?: string;
  sideNote?: string;
  waitingSub?: string;
}

const SEEDS: ConfigSeed[] = [
  // --- ❤️ Team Health Check & 🗳️ Live Poll (hosted activities) ----------
  {
    id: 'team-health',
    kind: 'health',
    castEvent: 'game:healthSubmit',
    icon: '❤️',
    accent: 'green',
    title: 'Team Health Check',
    tagline: 'Rate how the team is really doing — communication, delivery, morale and more.',
    header: '❤️ Team Health Check',
    promptLead: 'Rate each area',
    startLabel: 'Start Health Check',
    progressVerb: 'submitted',
    everyoneDone: 'Everyone has submitted',
    revealLabel: 'Reveal Results',
    nextLabel: 'New Health Check',
    whoTitle: 'Who rated what',
    doneLabel: 'Submitted',
    sideNote: 'Ratings stay hidden until the host reveals them — anonymity on by default.',
    waitingSub: 'The host will start the health check when everyone’s here.',
  },
  {
    id: 'live-poll',
    kind: 'poll',
    castEvent: 'game:pollVote',
    icon: '🗳️',
    accent: 'purple',
    title: 'Live Poll',
    tagline: 'Ask the room a question and watch the votes land — one vote, real-time results.',
    header: '🗳️ Live Poll',
    promptLead: 'Your question',
    startLabel: 'Start Poll',
    progressVerb: 'voted',
    everyoneDone: 'Everyone has voted',
    revealLabel: 'Reveal Results',
    nextLabel: 'New Poll',
    whoTitle: 'Who voted what',
    doneLabel: 'Voted',
    sideNote: 'Votes stay hidden until the host reveals them — anonymous by default.',
    waitingSub: 'The host will start the poll when everyone’s here.',
  },

  // --- 🧊 Icebreakers -----------------------------------------------------
  {
    id: 'most-likely-to',
    kind: 'teammate',
    castEvent: 'game:pick',
    icon: '😂',
    accent: 'gold',
    title: 'Most Likely To',
    tagline: 'Vote for the teammate most likely to do it. Yes, that one.',
    header: '😂 Most Likely To',
    promptLead: 'Most likely to',
    startLabel: 'Start the First Prompt',
    revealLabel: 'Reveal the Votes',
    nextLabel: 'Next Prompt',
  },
  {
    id: 'team-superlatives',
    kind: 'teammate',
    castEvent: 'game:pick',
    icon: '🏅',
    accent: 'purple',
    title: 'Team Superlatives',
    tagline: 'Crown the teammate most likely to win every category.',
    header: '🏅 Team Superlatives',
    promptLead: 'Who is most likely to…',
  },
  {
    id: 'who-said-it',
    kind: 'teammate',
    castEvent: 'game:pick',
    icon: '💬',
    accent: 'blue',
    title: 'Who Said It?',
    tagline: 'Guess which teammate actually said that quote.',
    header: '💬 Who Said It?',
    promptLead: 'Who said it?',
  },
  {
    id: 'would-you-rather',
    kind: 'options',
    castEvent: 'game:choose',
    icon: '🤔',
    accent: 'gold',
    title: 'Would You Rather',
    tagline: 'Tough picks, hot takes, zero right answers.',
    header: '🤔 Would You Rather',
    promptLead: 'Would you rather…',
    startLabel: 'Start the First Dilemma',
    revealLabel: 'Reveal the Split',
    nextLabel: 'Next Dilemma',
  },
  {
    id: 'this-or-that',
    kind: 'options',
    castEvent: 'game:choose',
    icon: '⚖️',
    accent: 'purple',
    title: 'This or That',
    tagline: 'Pick a side and defend it for 10 seconds.',
    header: '⚖️ This or That',
    promptLead: 'This or that?',
  },
  {
    id: 'emoji-check-in',
    kind: 'options',
    castEvent: 'game:choose',
    icon: '🙂',
    accent: 'blue',
    title: 'Emoji Check-in',
    tagline: 'How are you really doing? Pick one emoji.',
    header: '🙂 Emoji Check-in',
    promptLead: 'Your check-in:',
  },
  {
    id: 'guess-the-mood',
    kind: 'options',
    castEvent: 'game:choose',
    icon: '🎭',
    accent: 'green',
    title: 'Guess the Mood',
    tagline: 'Rate the vibe. See who reads the room best.',
    header: '🎭 Guess the Mood',
    promptLead: 'How’s the vibe?',
  },
  {
    id: 'team-trivia',
    kind: 'quiz',
    castEvent: 'game:answer',
    icon: '🧠',
    accent: 'gold',
    title: 'Team Trivia',
    tagline: 'Trivia about the team, for the team.',
    header: '🧠 Team Trivia',
    promptLead: 'Question:',
  },
  {
    id: 'odd-one-out',
    kind: 'quiz',
    castEvent: 'game:answer',
    icon: '🥷',
    accent: 'purple',
    title: 'Odd One Out',
    tagline: 'Four options. Three fit. Find the imposter.',
    header: '🥷 Odd One Out',
    promptLead: 'Which doesn’t belong?',
  },
  {
    id: 'two-truths-and-a-lie',
    kind: 'free',
    castEvent: 'game:submit',
    voteEvent: 'game:pick',
    hasVote: true,
    icon: '🕵️',
    accent: 'gold',
    title: 'Two Truths & a Lie',
    tagline: 'Spot the lie before the room votes you out.',
    header: '🕵️ Two Truths & a Lie',
    promptLead: 'Two truths and a lie:',
    revealLabel: 'Reveal the Statements',
    nextLabel: 'Next Round',
    whoTitle: 'Who said what',
    doneLabel: 'Shared',
  },
  {
    id: 'guess-who',
    kind: 'free',
    castEvent: 'game:submit',
    icon: '🫣',
    accent: 'purple',
    title: 'Guess Who',
    tagline: 'A teammate describes themselves — the room guesses who.',
    header: '🫣 Guess Who',
    promptLead: 'Describe yourself without naming yourself:',
    revealLabel: 'Reveal the Clues',
    nextLabel: 'Next Clue',
    whoTitle: 'Who wrote what',
    doneLabel: 'Wrote',
  },
  {
    id: 'who-knows-the-team-best',
    kind: 'quiz',
    castEvent: 'game:answer',
    icon: '🎓',
    accent: 'blue',
    title: 'Who Knows the Team Best?',
    tagline: 'Answer team questions. Compare answers. Laugh.',
    header: '🎓 Who Knows the Team Best?',
    promptLead: 'Question:',
  },
  {
    id: 'human-bingo',
    kind: 'free',
    castEvent: 'game:submit',
    icon: '🟩',
    accent: 'green',
    title: 'Human Bingo',
    tagline: 'Fill your card with teammates who match the squares.',
    header: '🟩 Human Bingo',
    promptLead: 'Claim your square:',
    revealLabel: 'Reveal the Squares',
    nextLabel: 'Next Square',
    whoTitle: 'Who claimed what',
    doneLabel: 'Claimed',
  },
  {
    id: 'one-word-check-in',
    kind: 'free',
    castEvent: 'game:submit',
    icon: '🗣️',
    accent: 'gold',
    title: 'One Word Check-in',
    tagline: 'Describe your week in a single word. Go.',
    header: '🗣️ One Word Check-in',
    promptLead: 'Your one word:',
    revealLabel: 'Reveal the Words',
    nextLabel: 'Next Word',
    whoTitle: 'Who said what',
    doneLabel: 'Said',
  },
  {
    id: 'rose-thorn-bud',
    kind: 'free',
    castEvent: 'game:submit',
    icon: '🌹',
    accent: 'purple',
    title: 'Rose, Thorn & Bud',
    tagline: 'Share a win, a struggle and something you look forward to.',
    header: '🌹 Rose, Thorn & Bud',
    promptLead: 'Your rose, thorn and bud:',
    revealLabel: 'Reveal the Shares',
    nextLabel: 'Next Round',
    whoTitle: 'Who shared what',
    doneLabel: 'Shared',
  },
  {
    id: 'high-low-buffalo',
    kind: 'free',
    castEvent: 'game:submit',
    icon: '🦬',
    accent: 'blue',
    title: 'High, Low, Buffalo',
    tagline: 'The classic daily standup round, gamified.',
    header: '🦬 High, Low, Buffalo',
    promptLead: 'Your high, low and buffalo:',
    revealLabel: 'Reveal the Shares',
    nextLabel: 'Next Round',
    whoTitle: 'Who shared what',
    doneLabel: 'Shared',
  },

  // --- ⚡ Fast Reaction & Speed -------------------------------------------
  {
    id: 'quick-math',
    kind: 'quiz',
    castEvent: 'game:answer',
    icon: '🧮',
    accent: 'green',
    title: 'Quick Math',
    tagline: 'Arithmetic under pressure — calculators banned.',
    header: '🧮 Quick Math',
    promptLead: 'Solve:',
  },
  {
    id: 'speed-quiz',
    kind: 'quiz',
    castEvent: 'game:answer',
    icon: '⏱️',
    accent: 'gold',
    title: 'Speed Quiz',
    tagline: 'A quiz where every second counts.',
    header: '⏱️ Speed Quiz',
    promptLead: 'Question:',
  },
  {
    id: 'word-scramble',
    kind: 'quiz',
    castEvent: 'game:answer',
    icon: '🔀',
    accent: 'purple',
    title: 'Word Scramble',
    tagline: 'Unscramble the word before the timer runs out.',
    header: '🔀 Word Scramble',
    promptLead: 'Unscramble:',
  },
  {
    id: 'anagram-race',
    kind: 'quiz',
    castEvent: 'game:answer',
    icon: '🔄',
    accent: 'blue',
    title: 'Anagram Race',
    tagline: 'Rearrange the letters. Race your teammates.',
    header: '🔄 Anagram Race',
    promptLead: 'Anagram:',
  },
  {
    id: 'missing-letter',
    kind: 'quiz',
    castEvent: 'game:answer',
    icon: '🔤',
    accent: 'green',
    title: 'Missing Letter',
    tagline: 'Spot the letter that keeps the word alive.',
    header: '🔤 Missing Letter',
    promptLead: 'Which letter completes it?',
  },
  {
    id: 'pattern-puzzle',
    kind: 'quiz',
    castEvent: 'game:answer',
    icon: '🧩',
    accent: 'gold',
    title: 'Pattern Puzzle',
    tagline: 'Spot the pattern faster than everyone else.',
    header: '🧩 Pattern Puzzle',
    promptLead: 'What comes next?',
  },
  {
    id: 'fastest-finger',
    kind: 'quiz',
    castEvent: 'game:answer',
    icon: '👆',
    accent: 'gold',
    title: 'Fastest Finger',
    tagline: 'First to tap the right answer takes the point.',
    header: '👆 Fastest Finger',
    promptLead: 'Be quick — pick the right one:',
  },
  {
    id: 'memory-challenge',
    kind: 'free',
    castEvent: 'game:submit',
    icon: '🧠',
    accent: 'purple',
    title: 'Memory Challenge',
    tagline: 'Memorize the sequence. Then it disappears.',
    header: '🧠 Memory Challenge',
    promptLead: 'Memorize, then answer:',
    revealLabel: 'Reveal the Answers',
    nextLabel: 'Next Round',
    whoTitle: 'Who remembered what',
    doneLabel: 'Remembered',
  },
  {
    id: 'reaction-challenge',
    kind: 'free',
    castEvent: 'game:submit',
    icon: '⚡',
    accent: 'blue',
    title: 'Reaction Challenge',
    tagline: 'Tap when the screen changes. Don’t be last.',
    header: '⚡ Reaction Challenge',
    promptLead: 'React fast:',
    revealLabel: 'Reveal the Results',
    nextLabel: 'Next Round',
    whoTitle: 'Who reacted how',
    doneLabel: 'Reacted',
  },
  {
    id: 'typing-race',
    kind: 'free',
    castEvent: 'game:submit',
    icon: '⌨️',
    accent: 'green',
    title: 'Typing Race',
    tagline: 'First to type the sentence wins the round.',
    header: '⌨️ Typing Race',
    promptLead: 'Type this exactly:',
    revealLabel: 'Reveal the Runners',
    nextLabel: 'Next Sentence',
    whoTitle: 'Who typed what',
    doneLabel: 'Typed',
  },
  {
    id: 'category-blitz',
    kind: 'free',
    castEvent: 'game:submit',
    voteEvent: 'game:pick',
    hasVote: true,
    icon: '🎲',
    accent: 'gold',
    title: 'Category Blitz',
    tagline: 'Name something in the category — fast, fast, fast.',
    header: '🎲 Category Blitz',
    promptLead: 'Name something in the category:',
    revealLabel: 'Reveal the Answers',
    nextLabel: 'Next Category',
    whoTitle: 'Who answered what',
    doneLabel: 'Answered',
  },

  // --- 🧠 Guessing ---------------------------------------------------------
  {
    id: 'emoji-guess',
    kind: 'quiz',
    castEvent: 'game:answer',
    icon: '🫠',
    accent: 'gold',
    title: 'Emoji Guess',
    tagline: 'Decode the movie, phrase or song from emojis.',
    header: '🫠 Emoji Guess',
    promptLead: 'Decode:',
  },
  {
    id: 'movie-guess',
    kind: 'quiz',
    castEvent: 'game:answer',
    icon: '🎬',
    accent: 'purple',
    title: 'Movie Guess',
    tagline: 'Guess the film from a single screenshot.',
    header: '🎬 Movie Guess',
    promptLead: 'Which movie?',
  },
  {
    id: 'logo-guess',
    kind: 'quiz',
    castEvent: 'game:answer',
    icon: '🏷️',
    accent: 'blue',
    title: 'Logo Guess',
    tagline: 'Zoomed-out logos. Can you name them all?',
    header: '🏷️ Logo Guess',
    promptLead: 'Which logo?',
  },
  {
    id: 'famous-person-guess',
    kind: 'quiz',
    castEvent: 'game:answer',
    icon: '🌟',
    accent: 'green',
    title: 'Famous Person Guess',
    tagline: 'Clues drop one by one. Guess before the room does.',
    header: '🌟 Famous Person Guess',
    promptLead: 'Who is it?',
  },
  {
    id: 'country-guess',
    kind: 'quiz',
    castEvent: 'game:answer',
    icon: '🌍',
    accent: 'gold',
    title: 'Country Guess',
    tagline: 'Guess the country from a shape, flag or food.',
    header: '🌍 Country Guess',
    promptLead: 'Which country?',
  },
  {
    id: 'image-guess',
    kind: 'quiz',
    castEvent: 'game:answer',
    icon: '🖼️',
    accent: 'purple',
    title: 'Image Guess',
    tagline: 'What is this a photo of? Be specific.',
    header: '🖼️ Image Guess',
    promptLead: 'What is it?',
  },
  {
    id: 'zoomed-in-guess',
    kind: 'quiz',
    castEvent: 'game:answer',
    icon: '🔬',
    accent: 'blue',
    title: 'Zoomed-In Guess',
    tagline: 'Extreme close-ups of everyday objects.',
    header: '🔬 Zoomed-In Guess',
    promptLead: 'What is this?',
  },
  {
    id: 'mystery-word',
    kind: 'quiz',
    castEvent: 'game:answer',
    icon: '🕵️‍♀️',
    accent: 'green',
    title: 'Mystery Word',
    tagline: 'One word, endless guesses, shared letters only.',
    header: '🕵️‍♀️ Mystery Word',
    promptLead: 'What’s the word?',
  },
  {
    id: 'higher-or-lower',
    kind: 'quiz',
    castEvent: 'game:answer',
    icon: '📈',
    accent: 'gold',
    title: 'Higher or Lower',
    tagline: 'Guess whether the number goes up or down.',
    header: '📈 Higher or Lower',
    promptLead: 'Higher or lower?',
  },
  {
    id: 'song-guess',
    kind: 'quiz',
    castEvent: 'game:answer',
    icon: '🎵',
    accent: 'purple',
    title: 'Song Guess',
    tagline: 'Name that tune — first notes only.',
    header: '🎵 Song Guess',
    promptLead: 'Name that tune:',
  },
  {
    id: 'sound-guess',
    kind: 'quiz',
    castEvent: 'game:answer',
    icon: '🔊',
    accent: 'blue',
    title: 'Sound Guess',
    tagline: 'Name it by sound alone.',
    header: '🔊 Sound Guess',
    promptLead: 'What sound is this?',
  },
  {
    id: '20-questions',
    kind: 'free',
    castEvent: 'game:submit',
    icon: '❓',
    accent: 'green',
    title: '20 Questions',
    tagline: 'Twenty yes-or-no questions to crack the answer.',
    header: '❓ 20 Questions',
    promptLead: 'Your final guess:',
    revealLabel: 'Reveal the Guesses',
    nextLabel: 'Next Mystery',
    whoTitle: 'Who guessed what',
    doneLabel: 'Guessed',
  },

  // --- 😂 Funny & Social ---------------------------------------------------
  {
    id: 'bug-or-feature',
    kind: 'options',
    castEvent: 'game:choose',
    icon: '🐛',
    accent: 'gold',
    title: 'Bug or Feature?',
    tagline: 'Is it broken or is it intended? The team decides.',
    header: '🐛 Bug or Feature?',
    promptLead: 'Bug or feature?',
  },
  {
    id: 'caption-this',
    kind: 'free',
    castEvent: 'game:submit',
    voteEvent: 'game:pick',
    hasVote: true,
    icon: '🖊️',
    accent: 'gold',
    title: 'Caption This',
    tagline: 'Everyone captions the same image. Vote the best.',
    header: '🖊️ Caption This',
    promptLead: 'Caption this:',
    progressVerb: 'submitted',
    everyoneDone: 'Everyone has submitted',
    revealLabel: 'Reveal the Captions',
    nextLabel: 'Next Caption',
    whoTitle: 'Who captioned what',
    doneLabel: 'Captioned',
  },
  {
    id: 'bad-advice',
    kind: 'free',
    castEvent: 'game:submit',
    voteEvent: 'game:pick',
    hasVote: true,
    icon: '🙃',
    accent: 'purple',
    title: 'Bad Advice',
    tagline: 'Give the worst possible advice. On purpose.',
    header: '🙃 Bad Advice',
    promptLead: 'Give the worst advice for…',
    revealLabel: 'Reveal the Advice',
    nextLabel: 'Next Dilemma',
    whoTitle: 'Who advised what',
    doneLabel: 'Advised',
  },
  {
    id: 'wrong-answers-only',
    kind: 'free',
    castEvent: 'game:submit',
    voteEvent: 'game:pick',
    hasVote: true,
    icon: '🚫',
    accent: 'blue',
    title: 'Wrong Answers Only',
    tagline: 'Answer trivia as incorrectly as possible.',
    header: '🚫 Wrong Answers Only',
    promptLead: 'Answer incorrectly:',
    revealLabel: 'Reveal the Answers',
    nextLabel: 'Next Question',
    whoTitle: 'Who answered what',
    doneLabel: 'Answered',
  },
  {
    id: 'finish-the-sentence',
    kind: 'free',
    castEvent: 'game:submit',
    voteEvent: 'game:pick',
    hasVote: true,
    icon: '✂️',
    accent: 'green',
    title: 'Finish the Sentence',
    tagline: 'Start a sentence, let the team finish it hilariously.',
    header: '✂️ Finish the Sentence',
    promptLead: 'Finish this sentence:',
    revealLabel: 'Reveal the Endings',
    nextLabel: 'Next Sentence',
    whoTitle: 'Who finished what',
    doneLabel: 'Finished',
  },
  {
    id: 'complete-the-meme',
    kind: 'free',
    castEvent: 'game:submit',
    voteEvent: 'game:pick',
    hasVote: true,
    icon: '🎭',
    accent: 'gold',
    title: 'Complete the Meme',
    tagline: 'Top text, bottom text, your best lines.',
    header: '🎭 Complete the Meme',
    promptLead: 'The meme is set. Your line:',
    revealLabel: 'Reveal the Lines',
    nextLabel: 'Next Meme',
    whoTitle: 'Who wrote what',
    doneLabel: 'Wrote',
  },
  {
    id: 'pun-battle',
    kind: 'free',
    castEvent: 'game:submit',
    voteEvent: 'game:pick',
    hasVote: true,
    icon: '🎤',
    accent: 'purple',
    title: 'Pun Battle',
    tagline: 'Best pun wins the round. No groaning allowed.',
    header: '🎤 Pun Battle',
    promptLead: 'Your best pun for…',
    revealLabel: 'Reveal the Puns',
    nextLabel: 'Next Pun',
    whoTitle: 'Who pun-ished what',
    doneLabel: 'Punned',
  },
  {
    id: 'roast-the-scenario',
    kind: 'free',
    castEvent: 'game:submit',
    voteEvent: 'game:pick',
    hasVote: true,
    icon: '🔥',
    accent: 'blue',
    title: 'Roast the Scenario',
    tagline: 'The most awkward work situation — roast it.',
    header: '🔥 Roast the Scenario',
    promptLead: 'Roast this:',
    revealLabel: 'Reveal the Roasts',
    nextLabel: 'Next Roast',
    whoTitle: 'Who roasted what',
    doneLabel: 'Roasted',
  },
  {
    id: 'excuse-generator',
    kind: 'free',
    castEvent: 'game:submit',
    voteEvent: 'game:pick',
    hasVote: true,
    icon: '🦥',
    accent: 'green',
    title: 'Excuse Generator',
    tagline: 'Generate excuses, vote the most believable.',
    header: '🦥 Excuse Generator',
    promptLead: 'Your excuse for…',
    revealLabel: 'Reveal the Excuses',
    nextLabel: 'Next Excuse',
    whoTitle: 'Who excused what',
    doneLabel: 'Excused',
  },
  {
    id: 'office-excuse-battle',
    kind: 'free',
    castEvent: 'game:submit',
    voteEvent: 'game:pick',
    hasVote: true,
    icon: '🐶',
    accent: 'gold',
    title: 'Office Excuse Battle',
    tagline: '“The dog ate my ticket” — make it work.',
    header: '🐶 Office Excuse Battle',
    promptLead: 'Your best office excuse for…',
    revealLabel: 'Reveal the Excuses',
    nextLabel: 'Next Excuse',
    whoTitle: 'Who excused what',
    doneLabel: 'Excused',
  },
  {
    id: 'fake-product',
    kind: 'free',
    castEvent: 'game:submit',
    voteEvent: 'game:pick',
    hasVote: true,
    icon: '📦',
    accent: 'purple',
    title: 'Fake Product',
    tagline: 'Invent a ridiculous product and pitch it.',
    header: '📦 Fake Product',
    promptLead: 'Invent a product for…',
    revealLabel: 'Reveal the Products',
    nextLabel: 'Next Product',
    whoTitle: 'Who invented what',
    doneLabel: 'Invented',
  },
  {
    id: 'fake-startup',
    kind: 'free',
    castEvent: 'game:submit',
    voteEvent: 'game:pick',
    hasVote: true,
    icon: '🚀',
    accent: 'blue',
    title: 'Fake Startup',
    tagline: 'Pitch a startup so bad it’s brilliant.',
    header: '🚀 Fake Startup',
    promptLead: 'Pitch a startup for…',
    revealLabel: 'Reveal the Pitches',
    nextLabel: 'Next Pitch',
    whoTitle: 'Who pitched what',
    doneLabel: 'Pitched',
  },
  {
    id: 'worst-feature-ever',
    kind: 'free',
    castEvent: 'game:submit',
    voteEvent: 'game:pick',
    hasVote: true,
    icon: '💣',
    accent: 'green',
    title: 'Worst Feature Ever',
    tagline: 'Design the feature no user asked for.',
    header: '💣 Worst Feature Ever',
    promptLead: 'The worst feature for…',
    revealLabel: 'Reveal the Features',
    nextLabel: 'Next Feature',
    whoTitle: 'Who designed what',
    doneLabel: 'Designed',
  },
  {
    id: 'developer-translator',
    kind: 'free',
    castEvent: 'game:submit',
    voteEvent: 'game:pick',
    hasVote: true,
    icon: '🔁',
    accent: 'gold',
    title: 'Developer Translator',
    tagline: 'Translate “it works on my machine” into business speak.',
    header: '🔁 Developer Translator',
    promptLead: 'Translate this dev phrase:',
    revealLabel: 'Reveal the Translations',
    nextLabel: 'Next Phrase',
    whoTitle: 'Who translated what',
    doneLabel: 'Translated',
  },

  // --- 💻 Developer --------------------------------------------------------
  {
    id: 'code-trivia',
    kind: 'quiz',
    castEvent: 'game:answer',
    icon: '📚',
    accent: 'gold',
    title: 'Code Trivia',
    tagline: 'Programming history, languages and lore.',
    header: '📚 Code Trivia',
    promptLead: 'Question:',
  },
  {
    id: 'tech-acronym-quiz',
    kind: 'quiz',
    castEvent: 'game:answer',
    icon: '🔡',
    accent: 'blue',
    title: 'Tech Acronym Quiz',
    tagline: 'What does that three-letter acronym mean?',
    header: '🔡 Tech Acronym Quiz',
    promptLead: 'What does it stand for?',
  },
  {
    id: 'http-status-challenge',
    kind: 'quiz',
    castEvent: 'game:answer',
    icon: '🔣',
    accent: 'purple',
    title: 'HTTP Status Challenge',
    tagline: 'What status code does that situation deserve?',
    header: '🔣 HTTP Status Challenge',
    promptLead: 'Which status?',
  },
  {
    id: 'guess-the-output',
    kind: 'quiz',
    castEvent: 'game:answer',
    icon: '🖥️',
    accent: 'green',
    title: 'Guess the Output',
    tagline: 'Read the snippet. Predict the console output.',
    header: '🖥️ Guess the Output',
    promptLead: 'What prints?',
  },
  {
    id: 'guess-the-error',
    kind: 'quiz',
    castEvent: 'game:answer',
    icon: '🚨',
    accent: 'gold',
    title: 'Guess the Error',
    tagline: 'A stack trace, one chance. What broke?',
    header: '🚨 Guess the Error',
    promptLead: 'What broke?',
  },
  {
    id: 'tech-logo-guess',
    kind: 'quiz',
    castEvent: 'game:answer',
    icon: '🔷',
    accent: 'gold',
    title: 'Tech Logo Guess',
    tagline: 'Frameworks, clouds and tools — by logo.',
    header: '🔷 Tech Logo Guess',
    promptLead: 'Which tech?',
  },
  {
    id: 'programming-language-guess',
    kind: 'quiz',
    castEvent: 'game:answer',
    icon: '🐍',
    accent: 'purple',
    title: 'Programming Language Guess',
    tagline: 'Name the language from its quirkiest snippet.',
    header: '🐍 Programming Language Guess',
    promptLead: 'Which language?',
  },
  {
    id: 'guess-the-git-command',
    kind: 'quiz',
    castEvent: 'game:answer',
    icon: '🔀',
    accent: 'blue',
    title: 'Guess the Git Command',
    tagline: 'Untangle the mess with the right command.',
    header: '🔀 Guess the Git Command',
    promptLead: 'Which command?',
  },
  {
    id: 'regex-challenge',
    kind: 'quiz',
    castEvent: 'game:answer',
    icon: '🎯',
    accent: 'green',
    title: 'Regex Challenge',
    tagline: 'Match the pattern. Escape the chaos.',
    header: '🎯 Regex Challenge',
    promptLead: 'Which regex matches?',
  },
  {
    id: 'sql-challenge',
    kind: 'quiz',
    castEvent: 'game:answer',
    icon: '🗄️',
    accent: 'gold',
    title: 'SQL Challenge',
    tagline: 'Write the query that answers the question.',
    header: '🗄️ SQL Challenge',
    promptLead: 'Which query?',
  },
  {
    id: 'debugging-race',
    kind: 'quiz',
    castEvent: 'game:answer',
    icon: '🐞',
    accent: 'purple',
    title: 'Debugging Race',
    tagline: 'Find the bug before your teammates do.',
    header: '🐞 Debugging Race',
    promptLead: 'Where’s the bug?',
  },
  {
    id: 'code-scramble',
    kind: 'quiz',
    castEvent: 'game:answer',
    icon: '🔀',
    accent: 'blue',
    title: 'Code Scramble',
    tagline: 'Rearrange the lines into working code.',
    header: '🔀 Code Scramble',
    promptLead: 'Which option is valid?',
  },
  {
    id: 'guess-the-framework',
    kind: 'quiz',
    castEvent: 'game:answer',
    icon: '🧱',
    accent: 'green',
    title: 'Guess the Framework',
    tagline: 'Identify the framework from its boilerplate.',
    header: '🧱 Guess the Framework',
    promptLead: 'Which framework?',
  },
  {
    id: 'stack-overflow-challenge',
    kind: 'quiz',
    castEvent: 'game:answer',
    icon: '📋',
    accent: 'gold',
    title: 'Stack Overflow Challenge',
    tagline: 'Match the question to its legendary answer.',
    header: '📋 Stack Overflow Challenge',
    promptLead: 'What’s the answer?',
  },
  {
    id: 'developer-meme-guess',
    kind: 'quiz',
    castEvent: 'game:answer',
    icon: '😅',
    accent: 'purple',
    title: 'Developer Meme Guess',
    tagline: 'Caption, identify and rate the dev memes.',
    header: '😅 Developer Meme Guess',
    promptLead: 'What’s the meme?',
  },

  // --- 🎯 Estimation -------------------------------------------------------
  {
    id: 'closest-wins',
    kind: 'estimate',
    castEvent: 'game:guess',
    icon: '🎯',
    accent: 'gold',
    title: 'Closest Wins',
    tagline: 'Estimate, compare, closest takes the point.',
    header: '🎯 Closest Wins',
    promptLead: 'Your best guess:',
  },
  {
    id: 'how-many',
    kind: 'estimate',
    castEvent: 'game:guess',
    icon: '🫙',
    accent: 'blue',
    title: 'How Many?',
    tagline: 'Jelly beans in the jar. Guess the count.',
    header: '🫙 How Many?',
    promptLead: 'How many?',
  },
  {
    id: 'price-is-right',
    kind: 'estimate',
    castEvent: 'game:guess',
    icon: '💸',
    accent: 'green',
    title: 'Price Is Right',
    tagline: 'Guess the price — without going over.',
    header: '💸 Price Is Right',
    promptLead: 'How much?',
  },
  {
    id: 'estimation-battle',
    kind: 'estimate',
    castEvent: 'game:guess',
    icon: '⚔️',
    accent: 'purple',
    title: 'Estimation Battle',
    tagline: 'Everyone estimates. Closest to the truth wins.',
    header: '⚔️ Estimation Battle',
    promptLead: 'Your best guess:',
  },
  {
    id: 'team-estimation',
    kind: 'estimate',
    castEvent: 'game:guess',
    icon: '🤝',
    accent: 'green',
    title: 'Team Estimation',
    tagline: 'Estimate as a team and defend your number.',
    header: '🤝 Team Estimation',
    promptLead: 'Your estimate:',
  },
  {
    id: 'higher-lower',
    kind: 'quiz',
    castEvent: 'game:answer',
    icon: '↕️',
    accent: 'blue',
    title: 'Higher / Lower',
    tagline: 'Estimate the stat, then guess higher or lower.',
    header: '↕️ Higher / Lower',
    promptLead: 'Higher or lower?',
  },

  // --- 🎨 Creative ---------------------------------------------------------
  {
    id: 'draw-and-guess',
    kind: 'free',
    castEvent: 'game:submit',
    voteEvent: 'game:pick',
    hasVote: true,
    icon: '🎨',
    accent: 'gold',
    title: 'Draw & Guess',
    tagline: 'Sketch it fast, guess it faster.',
    header: '🎨 Draw & Guess',
    promptLead: 'Describe the scene:',
    revealLabel: 'Reveal the Scenes',
    nextLabel: 'Next Scene',
    whoTitle: 'Who described what',
    doneLabel: 'Described',
  },
  {
    id: 'one-line-story',
    kind: 'free',
    castEvent: 'game:submit',
    voteEvent: 'game:pick',
    hasVote: true,
    icon: '📖',
    accent: 'purple',
    title: 'One-Line Story',
    tagline: 'Everyone adds one line. Chaos becomes canon.',
    header: '📖 One-Line Story',
    promptLead: 'Continue the story:',
    revealLabel: 'Reveal the Lines',
    nextLabel: 'Next Line',
    whoTitle: 'Who wrote what',
    doneLabel: 'Wrote',
  },
  {
    id: 'story-chain',
    kind: 'free',
    castEvent: 'game:submit',
    voteEvent: 'game:pick',
    hasVote: true,
    icon: '⛓️',
    accent: 'blue',
    title: 'Story Chain',
    tagline: 'Pass the story around, one twist at a time.',
    header: '⛓️ Story Chain',
    promptLead: 'Add the next line:',
    revealLabel: 'Reveal the Lines',
    nextLabel: 'Next Line',
    whoTitle: 'Who added what',
    doneLabel: 'Added',
  },
  {
    id: 'build-a-story',
    kind: 'free',
    castEvent: 'game:submit',
    voteEvent: 'game:pick',
    hasVote: true,
    icon: '🏗️',
    accent: 'green',
    title: 'Build a Story',
    tagline: 'Vote on the best next beat for the group story.',
    header: '🏗️ Build a Story',
    promptLead: 'The next plot beat:',
    revealLabel: 'Reveal the Beats',
    nextLabel: 'Next Beat',
    whoTitle: 'Who built what',
    doneLabel: 'Built',
  },
  {
    id: 'doodle-battle',
    kind: 'free',
    castEvent: 'game:submit',
    voteEvent: 'game:pick',
    hasVote: true,
    icon: '✏️',
    accent: 'gold',
    title: 'Doodle Battle',
    tagline: 'Best doodle for the prompt wins the round.',
    header: '✏️ Doodle Battle',
    promptLead: 'Describe your doodle:',
    revealLabel: 'Reveal the Doodles',
    nextLabel: 'Next Doodle',
    whoTitle: 'Who doodled what',
    doneLabel: 'Doodled',
  },
  {
    id: 'logo-drawing',
    kind: 'free',
    castEvent: 'game:submit',
    voteEvent: 'game:pick',
    hasVote: true,
    icon: '🏷️',
    accent: 'purple',
    title: 'Logo Drawing',
    tagline: 'Recreate a famous logo from memory.',
    header: '🏷️ Logo Drawing',
    promptLead: 'Describe the logo:',
    revealLabel: 'Reveal the Logos',
    nextLabel: 'Next Logo',
    whoTitle: 'Who drew what',
    doneLabel: 'Drew',
  },
  {
    id: 'draw-without-words',
    kind: 'free',
    castEvent: 'game:submit',
    voteEvent: 'game:pick',
    hasVote: true,
    icon: '🔇',
    accent: 'blue',
    title: 'Draw Without Words',
    tagline: 'No letters, no numbers — only shapes.',
    header: '🔇 Draw Without Words',
    promptLead: 'Describe it with shapes only:',
    revealLabel: 'Reveal the Drawings',
    nextLabel: 'Next Drawing',
    whoTitle: 'Who drew what',
    doneLabel: 'Drew',
  },
  {
    id: 'describe-and-draw',
    kind: 'free',
    castEvent: 'game:submit',
    voteEvent: 'game:pick',
    hasVote: true,
    icon: '🗣️',
    accent: 'green',
    title: 'Describe & Draw',
    tagline: 'Describe it, teammate draws what they hear.',
    header: '🗣️ Describe & Draw',
    promptLead: 'Describe it precisely:',
    revealLabel: 'Reveal the Descriptions',
    nextLabel: 'Next Description',
    whoTitle: 'Who described what',
    doneLabel: 'Described',
  },
  {
    id: 'emoji-story',
    kind: 'free',
    castEvent: 'game:submit',
    voteEvent: 'game:pick',
    hasVote: true,
    icon: '🫧',
    accent: 'gold',
    title: 'Emoji Story',
    tagline: 'Tell a whole story using only emojis.',
    header: '🫧 Emoji Story',
    promptLead: 'Tell the story in emojis:',
    revealLabel: 'Reveal the Stories',
    nextLabel: 'Next Story',
    whoTitle: 'Who told what',
    doneLabel: 'Told',
  },
  {
    id: 'create-a-meme',
    kind: 'free',
    castEvent: 'game:submit',
    voteEvent: 'game:pick',
    hasVote: true,
    icon: '🖼️',
    accent: 'purple',
    title: 'Create a Meme',
    tagline: 'Template provided. Punchline is on you.',
    header: '🖼️ Create a Meme',
    promptLead: 'Your punchline:',
    revealLabel: 'Reveal the Memes',
    nextLabel: 'Next Meme',
    whoTitle: 'Who memed what',
    doneLabel: 'Memed',
  },
  {
    id: 'name-that-product',
    kind: 'free',
    castEvent: 'game:submit',
    voteEvent: 'game:pick',
    hasVote: true,
    icon: '🏷️',
    accent: 'blue',
    title: 'Name That Product',
    tagline: 'Invent a product, then invent its name.',
    header: '🏷️ Name That Product',
    promptLead: 'Invent a name for…',
    revealLabel: 'Reveal the Names',
    nextLabel: 'Next Product',
    whoTitle: 'Who named what',
    doneLabel: 'Named',
  },
  {
    id: 'tagline-battle',
    kind: 'free',
    castEvent: 'game:submit',
    voteEvent: 'game:pick',
    hasVote: true,
    icon: '💬',
    accent: 'green',
    title: 'Tagline Battle',
    tagline: 'One product, ten taglines, one winner.',
    header: '💬 Tagline Battle',
    promptLead: 'Your tagline for…',
    revealLabel: 'Reveal the Taglines',
    nextLabel: 'Next Product',
    whoTitle: 'Who wrote what',
    doneLabel: 'Wrote',
  },

  // --- 🔤 Word -------------------------------------------------------------
  {
    id: 'unscramble',
    kind: 'quiz',
    castEvent: 'game:answer',
    icon: '🫧',
    accent: 'gold',
    title: 'Unscramble',
    tagline: 'Mixed-up letters, one clear word.',
    header: '🫧 Unscramble',
    promptLead: 'Unscramble:',
  },
  {
    id: 'word-chain',
    kind: 'free',
    castEvent: 'game:submit',
    voteEvent: 'game:pick',
    hasVote: true,
    icon: '⛓️',
    accent: 'gold',
    title: 'Word Chain',
    tagline: 'Last letter becomes the next word’s first.',
    header: '⛓️ Word Chain',
    promptLead: 'Your link in the chain:',
    revealLabel: 'Reveal the Links',
    nextLabel: 'Next Link',
    whoTitle: 'Who linked what',
    doneLabel: 'Linked',
  },
  {
    id: 'word-association',
    kind: 'free',
    castEvent: 'game:submit',
    icon: '🧠',
    accent: 'purple',
    title: 'Word Association',
    tagline: 'Say the first word that comes to mind.',
    header: '🧠 Word Association',
    promptLead: 'First word for…',
    revealLabel: 'Reveal the Words',
    nextLabel: 'Next Word',
    whoTitle: 'Who said what',
    doneLabel: 'Said',
  },
  {
    id: 'last-letter',
    kind: 'free',
    castEvent: 'game:submit',
    voteEvent: 'game:pick',
    hasVote: true,
    icon: '🔚',
    accent: 'blue',
    title: 'Last Letter',
    tagline: 'New word, last letter of the previous one. Fast.',
    header: '🔚 Last Letter',
    promptLead: 'Start with the last letter:',
    revealLabel: 'Reveal the Words',
    nextLabel: 'Next Word',
    whoTitle: 'Who wrote what',
    doneLabel: 'Wrote',
  },
  {
    id: 'forbidden-word',
    kind: 'free',
    castEvent: 'game:submit',
    voteEvent: 'game:pick',
    hasVote: true,
    icon: '🚫',
    accent: 'green',
    title: 'Forbidden Word',
    tagline: 'Describe it without saying the obvious word.',
    header: '🚫 Forbidden Word',
    promptLead: 'Describe it — the word is banned:',
    revealLabel: 'Reveal the Descriptions',
    nextLabel: 'Next Word',
    whoTitle: 'Who described what',
    doneLabel: 'Described',
  },
  {
    id: 'hangman',
    kind: 'free',
    castEvent: 'game:submit',
    icon: '🪢',
    accent: 'gold',
    title: 'Hangman',
    tagline: 'The classic. One wrong guess from the gallows.',
    header: '🪢 Hangman',
    promptLead: 'Guess the word:',
    revealLabel: 'Reveal the Word',
    nextLabel: 'Next Word',
    whoTitle: 'Who guessed what',
    doneLabel: 'Guessed',
  },
  {
    id: 'wordle-multiplayer',
    kind: 'free',
    castEvent: 'game:submit',
    icon: '🟩',
    accent: 'purple',
    title: 'Wordle-style Multiplayer',
    tagline: 'Guess the word in five tries — together.',
    header: '🟩 Wordle-style',
    promptLead: 'Guess the word:',
    revealLabel: 'Reveal the Word',
    nextLabel: 'Next Word',
    whoTitle: 'Who guessed what',
    doneLabel: 'Guessed',
  },
  {
    id: 'alphabet-challenge',
    kind: 'free',
    castEvent: 'game:submit',
    voteEvent: 'game:pick',
    hasVote: true,
    icon: '🔠',
    accent: 'blue',
    title: 'Alphabet Challenge',
    tagline: 'Words in alphabetical order, under pressure.',
    header: '🔠 Alphabet Challenge',
    promptLead: 'Your word for…',
    revealLabel: 'Reveal the Words',
    nextLabel: 'Next Letter',
    whoTitle: 'Who wrote what',
    doneLabel: 'Wrote',
  },
  {
    id: 'categories',
    kind: 'free',
    castEvent: 'game:submit',
    voteEvent: 'game:pick',
    hasVote: true,
    icon: '🛑',
    accent: 'green',
    title: 'Categories',
    tagline: 'Stop! Name five things in the category.',
    header: '🛑 Categories',
    promptLead: 'Name something in the category:',
    revealLabel: 'Reveal the Answers',
    nextLabel: 'Next Category',
    whoTitle: 'Who answered what',
    doneLabel: 'Answered',
  },
  {
    id: 'rhyming-battle',
    kind: 'free',
    castEvent: 'game:submit',
    voteEvent: 'game:pick',
    hasVote: true,
    icon: '🎤',
    accent: 'gold',
    title: 'Rhyming Battle',
    tagline: 'Rhyme on command or bow out.',
    header: '🎤 Rhyming Battle',
    promptLead: 'Rhyme about…',
    revealLabel: 'Reveal the Rhymes',
    nextLabel: 'Next Rhyme',
    whoTitle: 'Who rhymed what',
    doneLabel: 'Rhymed',
  },
  {
    id: 'guess-the-word',
    kind: 'quiz',
    castEvent: 'game:answer',
    icon: '🔤',
    accent: 'blue',
    title: 'Guess the Word',
    tagline: 'Clues drop, letters fill, team guesses.',
    header: '🔤 Guess the Word',
    promptLead: 'What’s the word?',
  },
  {
    id: 'synonym-race',
    kind: 'quiz',
    castEvent: 'game:answer',
    icon: '🔄',
    accent: 'green',
    title: 'Synonym Race',
    tagline: 'Another way to say it — race the clock.',
    header: '🔄 Synonym Race',
    promptLead: 'A synonym for…',
  },
  {
    id: 'opposite-challenge',
    kind: 'quiz',
    castEvent: 'game:answer',
    icon: '⚖️',
    accent: 'purple',
    title: 'Opposite Challenge',
    tagline: 'Say the opposite. Faster than everyone.',
    header: '⚖️ Opposite Challenge',
    promptLead: 'The opposite of…',
  },

  // --- 🏆 Competitive ------------------------------------------------------
  {
    id: 'trivia-battle',
    kind: 'quiz',
    castEvent: 'game:answer',
    icon: '⚔️',
    accent: 'gold',
    title: 'Trivia Battle',
    tagline: 'Head-to-head trivia across every topic.',
    header: '⚔️ Trivia Battle',
    promptLead: 'Question:',
  },
  {
    id: 'quiz-royale',
    kind: 'quiz',
    castEvent: 'game:answer',
    icon: '👑',
    accent: 'purple',
    title: 'Quiz Royale',
    tagline: 'Everyone answers. Wrong answers get voted out.',
    header: '👑 Quiz Royale',
    promptLead: 'Question:',
  },
  {
    id: 'survival-quiz',
    kind: 'quiz',
    castEvent: 'game:answer',
    icon: '🪖',
    accent: 'blue',
    title: 'Survival Quiz',
    tagline: 'Last one standing with correct answers wins.',
    header: '🪖 Survival Quiz',
    promptLead: 'Question:',
  },
  {
    id: 'last-player-standing',
    kind: 'quiz',
    castEvent: 'game:answer',
    icon: '🏅',
    accent: 'green',
    title: 'Last Player Standing',
    tagline: 'Keep answering, keep surviving.',
    header: '🏅 Last Player Standing',
    promptLead: 'Question:',
  },
  {
    id: 'point-rush',
    kind: 'quiz',
    castEvent: 'game:answer',
    icon: '⚡',
    accent: 'gold',
    title: 'Point Rush',
    tagline: 'Stack points fast in rapid-fire rounds.',
    header: '⚡ Point Rush',
    promptLead: 'Question:',
  },
  {
    id: 'team-vs-team-quiz',
    kind: 'quiz',
    castEvent: 'game:answer',
    icon: '🆚',
    accent: 'purple',
    title: 'Team vs Team Quiz',
    tagline: 'Two teams, one buzzer, bragging rights.',
    header: '🆚 Team vs Team Quiz',
    promptLead: 'Question:',
  },
  {
    id: 'speed-round',
    kind: 'quiz',
    castEvent: 'game:answer',
    icon: '⏩',
    accent: 'blue',
    title: 'Speed Round',
    tagline: 'Rapid questions, even faster answers.',
    header: '⏩ Speed Round',
    promptLead: 'Question:',
  },
  {
    id: 'lightning-round',
    kind: 'quiz',
    castEvent: 'game:answer',
    icon: '🌩️',
    accent: 'green',
    title: 'Lightning Round',
    tagline: 'No time to think — just answer.',
    header: '🌩️ Lightning Round',
    promptLead: 'Question:',
  },
  {
    id: 'knockout',
    kind: 'quiz',
    castEvent: 'game:answer',
    icon: '🥊',
    accent: 'gold',
    title: 'Knockout',
    tagline: 'One wrong answer and you’re out.',
    header: '🥊 Knockout',
    promptLead: 'Question:',
  },
  {
    id: 'leaderboard-challenge',
    kind: 'quiz',
    castEvent: 'game:answer',
    icon: '📊',
    accent: 'purple',
    title: 'Leaderboard Challenge',
    tagline: 'Climb the board round after round.',
    header: '📊 Leaderboard Challenge',
    promptLead: 'Question:',
  },
];

const CONFIGS: Record<string, GameConfig> = Object.fromEntries(
  SEEDS.map((seed) => {
    const d = KIND_DEFAULTS[seed.kind];
    return [
      seed.id,
      {
        id: seed.id,
        kind: seed.kind,
        castEvent: seed.castEvent,
        voteEvent: seed.voteEvent,
        hasVote: seed.hasVote,
        icon: seed.icon,
        accent: seed.accent,
        title: seed.title,
        tagline: seed.tagline,
        header: seed.header,
        promptLead: seed.promptLead,
        startLabel: seed.startLabel ?? d.startLabel,
        progressVerb: seed.progressVerb ?? d.progressVerb,
        everyoneDone: seed.everyoneDone ?? d.everyoneDone,
        revealLabel: seed.revealLabel ?? d.revealLabel,
        nextLabel: seed.nextLabel ?? d.nextLabel,
        whoTitle: seed.whoTitle ?? d.whoTitle,
        doneLabel: seed.doneLabel ?? d.doneLabel,
        sideNote: seed.sideNote ?? d.sideNote,
        waitingSub: seed.waitingSub ?? d.waitingSub,
      } satisfies GameConfig,
    ];
  }),
);

export const GAME_CONFIGS = CONFIGS;

export function getGameConfig(id: string): GameConfig | undefined {
  return CONFIGS[id];
}

/** The engine-backed live game ids, in catalog order. */
export const ENGINE_GAME_IDS = SEEDS.map((s) => s.id);
